version: '2.1'

services:
  dotnetcoreconsole:
    image: dotnetcoreconsole:dev
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - .\DotNetCoreConsole:C:\app
      - ~\.nuget\packages:c:\nuget\packages:ro
      - ${ONECOREMSVSMON_PATH}:C:\onecoremsvsmon:ro
    entrypoint: powershell -Command [System.Threading.Thread]::Sleep([System.Threading.Timeout]::Infinite)
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=windows"
      - "com.microsoft.visualstudio.targetframework=dotnetcore"
